{% set name = "responsefun" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxscheurer/responsefun/archive/v{{ version }}.tar.gz
  sha256: 77604b9b80fe2dc5bdabe5c77f31276e53e84f82f814e57d0fdb1aeae9879196

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >={{ python_min }}
    - adcc >=0.15.4
    - respondo >=0.0.4
    - numpy <=1.23.5
    - sympy
    - tqdm
    - anytree

test:
  imports:
    - responsefun
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - zarr
    - python {{ python_min }}

about:
  home: https://github.com/maxscheurer/responsefun
  summary: Fun with automatic evaluation of response functions in the ADC framework
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apapapostolou
    - maxscheurer
